services:
    admin.contest:
        class: Contest\AdminBundle\Admin\ContestAdmin
        arguments: [~, Contest\ContestBundle\Entity\Contest, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Contest }

    admin.image:
        class: Contest\AdminBundle\Admin\ImageAdmin
        arguments: [~, Contest\ContestBundle\Entity\Image, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Image }

    admin.category:
        class: Contest\AdminBundle\Admin\CategoryAdmin
        arguments: [~, Contest\ContestBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }