<?php

namespace Contest\ContestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestRepository extends EntityRepository
{
    public function findActives(){
        $date = new \DateTime;

        $qb = $this->createQueryBuilder('c')
            ->andWhere('c.beginDate <= :date')
            ->andWhere('c.endDate > :date');

        $qb->setParameter('date', $date->format('Y-m-d'));

        return $qb->getQuery()->getResult();
    }

    public function findFinished(){
        $date = new \DateTime;

        $qb = $this->createQueryBuilder('c')
            ->andWhere('c.endDate < :date')
            ->orderBy('c.endDate', 'DESC')
            ->setMaxResults(10);

        $qb->setParameter('date', $date->format('Y-m-d'));

        return $qb->getQuery()->getResult();
    }
}
