<?php

namespace Contest\ContestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
}
